### ISSUE TITLE
Assuming that `master` is the default branch

### ISSUE THREAD

**Issue by erikw** [tpope/git-bump#12]
https://github.com/tpope/git-bump/blob/cd0656cb27900f86260f2b5d8752547cc457e3ef/lib/git_bump.rb#L169

Nowadays the default branch for new GitHub repos is `main`.

**Comment by tpope** [comment]
The default Git branch is still `master`, but correct, this shouldn't be hard coded.

**Comment by tpope** [comment]
Oh I heard you, I just don't think we should go running to the biggest corporate overlord for our reference point.

Anyways, looks like I fixed this locally 6 months ago and never pushed.

**Comment by erikw** [comment]
Sweet. Thank you!
