### ISSUE TITLE
`git bump redo` fails on a project with no tags

### ISSUE THREAD

**Issue by abusalimov** [tpope/git-bump#8]
Hi,

Thank you for git-bump! I was searching for versioning best practices and came across your project. So I decided to give it a shot and try it on one of my projects.

Here is what I did:

```console
eldar@eldar-desktop:~/workspace/mybuild-git ─ (git: master) ───────────────────
$ git bump
Appears to be initial release.  Version number required.
eldar@eldar-desktop:~/workspace/mybuild-git ─ (git: master) ───────────────────
$ git bump 0.1
Looks like this is your first release.  Please add the version number to the
work tree (e.g., in your Makefile), stage your changes, and run git bump again.

If this isn't your first release, tag your most recent prior release so that
git bump can find it:

        git tag -s v1.2.3 8675309

```

OK, that's pretty clear so far.

Edit and stage...

```console
eldar@eldar-desktop:~/workspace/mybuild-git ─ (git: master) ───────────────────
$ git bump 0.1
[master 9e98236] mybuild-git 0.1
 1 file changed, 1 insertion(+), 1 deletion(-)
gpg: skipped "Eldar Abusalimov <eldar.abusalimov@gmail.com>": secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
error: unable to sign the tag
Error running Git.
```

Oops. I didn't use GPG before, and I end up having a release commit but no tag created. OK, there's a `git bump redo` command, may be that's what I want?

```console
eldar@eldar-desktop:~/workspace/mybuild-git ─ (git: master) ───────────────────
$ git bump redo
/var/lib/gems/1.9.1/gems/git-bump-1.0.0/lib/git_bump.rb:226:in `redo': undefined method `sha1' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/git-bump-1.0.0/lib/git_bump.rb:19:in `start'
	from /var/lib/gems/1.9.1/gems/git-bump-1.0.0/bin/git-bump:7:in `<top (required)>'
	from /usr/local/bin/git-bump:23:in `load'
	from /usr/local/bin/git-bump:23:in `<main>'
```

I've tried both 1.0.0 ruby gem and a code from `master` (bf793c10d36d2d944d9291227b89402a4284a7fc), reproduced on both.

**Comment by tpope** [comment]
The problem is that redo assumes the most recent bump successfully tagged. I made the error a bit less obnoxious but I'm not sure how to handle recovering from this situation. Perhaps we should `reset --soft HEAD^` on tag failure?

**Comment by tpope** [comment]
Let me know how the latest works for you.

**Comment by abusalimov** [comment]
> Perhaps we should reset --soft HEAD^ on tag failure?

That could be unpleasant in case the user has entered some release notes into that commit message. Not everyone realize that git actually retains every commit and how to restore it, i.e. its message.

I guess, the most friendly way for me personally would be to admit a failure as it is now, but also add a hint what to do to proceed or how to rollback manually. Something like you get on a conflict during rebase. That is, I'd expect roughly the following:

```
$ git bump 0.1
[master 9e98236] mybuild-git 0.1
 1 file changed, 1 insertion(+), 1 deletion(-)
gpg: skipped "Eldar Abusalimov <eldar.abusalimov@gmail.com>": secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
error: unable to sign the tag

Unable to create git tag. You can try to create it manually, with

	git tag --sign -m"$(git show --format=%B)" v0.1

To restore the original state, run

	git reset --soft HEAD^
```

Of course this would require to hand craft the hint (whether to use `--sign` or `--annotate`, m.b. specify the commit SHA explicitly, etc.), but I believe that's the most right and git-like way to talk to user.

**Comment by tpope** [comment]
Good point. I'm going with a shorter hint but feel free to expand, provided you stitch together the correct arguments to `git tag` (which may vary).

**Comment by abusalimov** [comment]
Works fine for me. Thank you!
