### ISSUE TITLE
Tag recent version and update a gem

### ISSUE THREAD

**Issue by abusalimov** [tpope/git-bump#9]
It would be nice to be able to install the most recent version from ruby gems, especially since there already were no commits to `master` for 1 year.

Personally I miss the unsigned tags feature introduced in 8d30b3ea424529a606620bdb8a7aa98bdd8b97f3.

Thanks in advance!

**Comment by tpope** [comment]
Sure, perhaps after #8 is resolved.

**Comment by abusalimov** [comment]
Ping!
